config/routes.rb
Char::Application.routes.draw do

  authenticated :user do
      root to: "dashboards#show", as: "authenticated_root"
  end

  root to: "blog#index"

  resources :blog

  devise_for :users

  resources :blueprints do
    resources :discussions
  end

  resources :posts do
    resources :revisions, only: [:index, :show]
    resources :reviews
  end

  resource :dashboard, only: [:show]

  resources :users, only: [:edit, :update, :show, :index]
end

app/models/blueprint.rb
class Blueprint < ActiveRecord::Base
  belongs_to :creator, class_name: User

  has_many :activities, as: :acted
  has_many :assignments
  has_many :assignees, through: :assignments
  has_many :discussions

  validates :status, presence: true
  validates :title, presence: true

  scope :unassigned, -> do
    joins(:assignments).select('blueprints.id').
      group('blueprints.id').having('count(assignmets.id) == 0')
  end
end

app/controllers/blueprints_controller.rb
class BlueprintsController < ApplicationController

  before_action :authorize
  before_action :get_blueprints

  def index
    respond_with(@visible_blueprints)
  end

  def show
    @blueprint = @visible_blueprints.find(params[:id])
    respond_with(@blueprint)
  end

  def new
    @blueprint = current_user.blueprints.new
    respond_with(@blueprint)
  end

  def edit
    @blueprint = @editable_blueprints.find(params[:id])
  end

  def create
    @blueprint = current_user.blueprints.new(blueprint_params)
    if @blueprint.save
      current_user.activities.create(acted: @blueprint, action: 'blueprint:create')
    end
    respond_with(@blueprint)
  end

  def update
    @blueprint = @editable_blueprints.find(params[:id])
    if @blueprint.update(blueprint_params)
      current_user.activities.create(acted: @blueprint, action: 'blueprint:update')
    end
    respond_with(@blueprint)
  end

  def destroy
    @blueprint = current_user.blueprints.find(params[:id])
    @blueprint.destroy
    respond_with(@blueprint)
  end

  private

  def blueprint_params
    params.require(:blueprint).permit(:title, :description, :status, :due_date, assignee_ids: [])
  end

  def get_blueprints
    @visible_blueprints = current_user.visible_blueprints
    @editable_blueprints = current_user.editable_blueprints
  end
end

app/helpers/blueprints_helper.rb
module BlueprintsHelper
  def status_text(text) 
    t("activerecord.attributes.blueprint.statuses.#{text}")
  end

  def status_label_classes(s)
    case s
    when 'approved'
      'label label-success'
    when 'dipproved'
      'label label-important'
    else
      'label'
    end
  end

  def status_label(s)
    content_tag :span, status_text(s), class: status_label_classes(s) 
  end

  def collectify_statuses(list)
    Hash[list.map{ |s| [status_text(s), s] }]
  end
end

app/views/blueprints/_blueprint.html.erb
<div class="media blueprint">
  <div class='media-body'>
    <div>
      <%= blueprint.title %>
      <div class="pull-left">
        <%= status_label(blueprint.status) %>
        <%= link_to t('helpers.links.edit_icon_html'), edit_blueprint_path(blueprint) %>
      </div>
    </div>
    <div>
      <% if blueprint.assignees.count > 0 %>
        <i class='icon-user'></i>
        <%= blueprint.assignees.pluck(:name).join ', ' %>
      <% else %>
        <i class='icon-user'></i> <%= t '.not_assigned' %>
      <% end %>

      <% if blueprint.due_date %>
        | <i class='icon-time'></i> <%= time_ago_in_words(blueprint.due_date) %>
      <% else %>
        | <i class='icon-time'></i> <%= t '.no_due_date' %>
      <% end %>
    </div>
  </div>
</div>

app/views/blueprints/_discussion.html.erb
<div class="row">
  <div ng-controller = 'BlueprintDiscussionsCtrl' class="span6 offset3">
    <h2>
      <%= t '.discussions' %>
      <a id="reloadBtn" ng-click='reload()' class='btn btn-mini' >
        <i class='icon-refresh'></i>
      </a>
    </h2>
    <div>
      <div ng-repeat="discussion in discussions" class='discussion media'>
        <div class='pull-right'>
          <img ng-src='{{ discussion.user.email | gravatarUrl }}' class="img-rounded media-object"></img>
        </div>
        <div class='media-body'>
          <div class='discussion-body'>
            <strong>{{discussion.user.name}}:</strong>
            <span ng-bind-html-unsafe="discussion.body | markdown"></span>
          </div>
          <div class='discussion-footer'>
            <i class='icon-time'></i> <time datetime='{{discussion.created_at}}'>{{discussion.created_at | timeAgo | persianNum }}</time>
          </div>
        </div>
      </div> <%# ng-repeat %>
    </div>

    <div>
      <form id='newDiscussionForm' ng-submit="createDiscussion()">
        <fieldset>
          <legend><%= t '.your_comment' %></legend>
          <div class='control-group media'>
            <div class='pull-right'>
              <img ng-src='{{ $window.gon.current_user.email | gravatarUrl }}' class="img-rounded media-object"></img>
            </div>
            <div class='media-body'>
              <div class='discussion-body'>
                <textarea rows=2 ng-model='discussionForm.body' class='input-block-level'></textarea>
              </div>
            </div>
          </div>
          <input type="submit" class="btn" value="<%= t '.send_your_comment' %>" />
        </fieldset>
      </form>
    </div>
  </div>
</div>

app/views/blueprints/_form.html.erb
<%= simple_form_for @blueprint, :html => { :class => 'form-vertical', 'ng-controller' => 'BlueprintEditorPrevCtrl' } do |f| %>
  <div class="row">
    <div class='form-inputs span9'>
      <%= f.input :title, input_html: {'ng-model' => 'blueprint.title', 'ng-initial' => @blueprint.title }%>
      <%= f.input :status, collection: collectify_statuses(Rails.configuration.blueprint_status) %>
      <%= markdown_help %>
      <%= f.input :description, input_html: { class: 'input-block-level wysiwym', rows: 8,
        'ng-model' => 'blueprint.description', 'ng-initial' => @blueprint.description } %>
      </div>
      <div class="form-inputs span3">
        <%= f.association :assignees, as: :check_boxes, collection: User.editorial %>
        <%= f.input :due_date, as: :date %>
      </div>
    </div>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                blueprints_path, :class => 'btn' %>
  </div>
  <div class='well preview'>
    <%= content_tag :h1 do %>
      {{blueprint.title}} <small><%= @blueprint.creator.name %></small>
    <% end %>
    <%= content_tag :div, '', 'ng-bind-html-unsafe' => 'blueprint.description | markdown' %>
  </div>
<% end %>

app/views/blueprints/edit.html.erb
<%- model_class = Blueprint -%>
<div class="page-header">
  <h1><%= t 'helpers.titles.edit', :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/blueprints/index.html.erb
<%- model_class = Blueprint -%>
<div class="page-header">
  <h1><%=t '.title' %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:creator) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <%= content_tag_for :tr, @visible_blueprints do |blueprint| %>
        <td><%= link_to blueprint.title, blueprint_path(blueprint) %></td>
        <td><%= truncate blueprint.description %></td>
        <td><%= blueprint.creator.name %></td>
        <td><%= status_label blueprint.status %></td>
        <td><%= l blueprint.created_at, format: :short %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit_html")),
                      edit_blueprint_path(blueprint), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy_html")),
                      blueprint_path(blueprint), method: :delete,
                      :data => { :confirm => t("helpers.links.confirm") },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
    <% end %>
  </tbody>
</table>

<%= link_to t("helpers.links.new_html"), new_blueprint_path, class: 'btn btn-primary' %>

app/views/blueprints/new.html.erb
<%- model_class = Blueprint -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/blueprints/show.html.erb
<%- model_class = Blueprint -%>
<div class="page-header">
  <h1><%= Blueprint.model_name.human %>: <%= @blueprint.title %> <%= status_label(@blueprint.status) %> <small><%= @blueprint.creator.name  %></small></h1>
</div>

<div class="row">
  <div class="span9">
    <div markdown><%= @blueprint.description %></div>
    <%= link_to t("helpers.links.edit_html"),
      edit_blueprint_path(@blueprint), :class => 'btn btn-mini' %>
  </div>
  <div class="span3">
    <h3><%= Blueprint.human_attribute_name :assignees %></h3>
    <% if @blueprint.assignees.count > 0 %>
      <ul class="unstyled">
        <%= content_tag_for :li, @blueprint.assignees do |a| %>
          <%= a.name %>
        <% end %>
      </ul>
    <% else %>
      <p>
        <em><%= t '.no_assignees' %></em>
      </p>
    <% end %>
    <%= link_to t("helpers.links.edit_html"),
      edit_blueprint_path(@blueprint), :class => 'btn btn-mini' %>
  </div>
</div>

<div class="form-actions">
  <%= link_to t("helpers.links.edit_html"),
              edit_blueprint_path(@blueprint), :class => 'btn' %>
  <%= link_to t("helpers.links.destroy_html"),
              blueprint_path(@blueprint),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<%= render 'discussion', blueprint: @blueprint %>