config/routes.rb
Char::Application.routes.draw do

  authenticated :user do
      root to: "dashboards#show", as: "authenticated_root"
  end

  root to: "blog#index"

  resources :blog

  devise_for :users

  resources :blueprints do
    resources :discussions
  end

  resources :posts do
    resources :revisions, only: [:index, :show]
    resources :reviews
  end

  resource :dashboard, only: [:show]

  resources :users, only: [:edit, :update, :show, :index]
end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController

  before_action :find_post

  def index
    respond_with @revisions
  end

  def show
    @revision = @revisions.find params[:id]
    respond_with @revision
  end

  private

  def find_post
    @post = current_user.visible_posts.find(params[:post_id])
    @revisions = @post.versions    
  end
end

app/helpers/revisions_helper.rb
module RevisionsHelper
  def show_diff(a,b)
    diff = Diffy::Diff.new(h(a),h(b), diff: ['--minimal', '-w', '-U10000'], include_plus_and_minus_in_html: true )
    diff.to_s(:html).html_safe
  end

  def previous_next_btn(rev)
    previous_link =  if rev.try(:previous)
      link_to(t('.previous_html'), post_revision_path(rev.item_id, rev.previous), class: 'btn')
    else
      link_to(t('.previous_html'), '#', class: 'btn disabled')
    end
    next_link = if rev.try(:next)
      link_to(t('.next_html'), post_revision_path(rev.item_id, rev.next), class: 'btn')
    else
      link_to(t('.next_html'), '#', class: 'btn disabled')
    end

    "#{previous_link} #{next_link}".html_safe
  end

  def terminator_name(rev)
    rev.terminator ? User.find(rev.terminator.to_i).name : t('.unknown_terminator')
  end

  def calc_diff(rev, attribute)
    diffed = if rev.event == 'create' || rev.changeset.include?(attribute.to_s)
               show_diff(*(rev.changeset[attribute.to_s]))
             else
               simple_format(rev.reify[attribute.to_sym])
             end
    diffed.html_safe
  end

  def event_name(rev)
    t("activerecord.attributes.version.events.#{rev.event}")
  end
end

app/views/revisions/index.html.erb
<div class="page-header">
  <h1><%=t '.title_html', title: link_to(@post.title, @post) %> <span class="badge"><%= @revisions.count %></span></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t '.index' %></th>
      <th><%= t '.who' %></th>
      <th><%= t '.event' %></th>
      <th><%= t '.created_at' %></th>
    </tr>
  </thead>
  <tbody>
    <% @revisions.each do |revision| %>
      <tr>
        <td><%= link_to "#{revision.id} (#{revision.index})", post_revision_path(@post, revision.id) %></td>
        <td><%= User.find(revision.originator).name if revision.originator %></td>
        <td><%= revision.event %></td>
        <td><%= l revision.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/revisions/show.html.erb
<div class="page-header">
  <h1><%= t '.title_html', title: @post.title , terminator: terminator_name(@revision) %></h1>
</div>
<div class='alert alert-block alert-info'>
  <%= content_tag :p, t('.sentence', terminator: terminator_name(@revision),
    event: event_name(@revision),
    created_at: l(@revision.created_at, format: :short))
  %>
  <p>
    <%= link_to t('.index'), post_revisions_path(@revision.item_id) %>
  </p>
  <p>
    <%= previous_next_btn(@revision) %>
  </p>
</div>
<h2><%= calc_diff(@revision, :title) %></h2>

<%= content_tag :div, calc_diff(@revision, :body), class: 'well' %>