config/routes.rb
Char::Application.routes.draw do

  authenticated :user do
      root to: "dashboards#show", as: "authenticated_root"
  end

  root to: "blog#index"

  resources :blog

  devise_for :users

  resources :blueprints do
    resources :discussions
  end

  resources :posts do
    resources :revisions, only: [:index, :show]
    resources :reviews
  end

  resource :dashboard, only: [:show]

  resources :users, only: [:edit, :update, :show, :index]
end

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/"><%= t :char %></a>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to t('.blog_html'), blog_index_path %></li>
        </ul>
        <ul class='nav pull-left'>
          <li><%= link_to t('.sign_up_html'), new_user_registration_path %></li>
          <li><%= link_to t('.sign_in_html'), new_user_session_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_user_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/"><%= t :char %></a>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to t('.dashboard_html'), dashboard_path %></li>
          <li><%= link_to t('.all_posts_html'), posts_path %></li>
          <li><%= link_to t('.blueprints_html'), blueprints_path %></li>
          <li><%= link_to t('.users_html'), users_path %></li>
          <li class='divider-vertical'></li>
          <li><%= link_to t('.post_new_html'), new_post_path %></li>
        </ul>
        <ul class='nav pull-left'>
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t '.hello', user: current_user.first_name %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to t('.profile_html'), user_path(current_user)%></li>
              <li><%= link_to t('.prefrences_html'), edit_user_path(current_user)%></li>
              <li><%= mail_to 'arashbm@gmail.com', t('.support_html'), subject: 'چارپایه ترکیده' %></li>
              <li class="divider"></li>
              <li><%= link_to t('.sign_out_html'), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fa" dir="rtl">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Char" %></title>
    <%= csrf_meta_tags %>

    <!-- Javascripts
    ================================================== -->
    <%= javascript_include_tag "application" %>

    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  </head>

  <body>

    <%= include_gon %>

    <header>
      <%= render (user_signed_in? ? 'layouts/user_navbar' : 'layouts/navbar') %>
    </header>

    <div id="container" class="container" data-current-user='<%= (current_user || {}).to_json %>' ng-app="char">
      <%= bootstrap_flash %>
      <%= content_tag :div, class: 'row' do %>
        <%= yield %>
      <% end %>

      <footer>
        <hr />
        <p>Char v1.3.3</p>
      </footer>

    </div> <!-- /container -->


  </body>
</html>